// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ughpxgxobtaxecbsgqca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVnaHB4Z3hvYnRheGVjYnNncWNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NDQ5NDgsImV4cCI6MjA2MzUyMDk0OH0.NdlmEQ5SJz3WH2s4QdcyyDkdPAkTdbmzOUu8J0cOIrI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);